included:
- Sources

# rule identifiers to exclude from running
disabled_rules:
    - file_length
    - cyclomatic_complexity
    - variable_name
    - todo
    - line_length
    - type_body_length
    - function_body_length

shorthand_operator: warning
superfluous_disable_command: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

nesting:
   type_level:
      warning: 2

line_length: 200

disabled_rules:
    - type_name
    - file_length
    - unused_setter_value

function_parameter_count:
   warning: 7
   error: 10