included:
- Sources

# rule identifiers to exclude from running
disabled_rules:
    - file_length
    - identifier_name
    - variable_name
    - todo
    - line_length
    - type_body_length
    - function_body_length
    - type_name
    - file_length
    - unused_setter_value

shorthand_operator: warning
superfluous_disable_command: warning

nesting:
   type_level:
      warning: 2

line_length: 200

function_parameter_count:
   warning: 7
   error: 10
